In [1]:
import pandas as pd

from functions import *

In [2]:
df = pd.read_csv("Datasets/fixtures.csv")
df = set_ELO(df)
winper = WinPer()
winper.to_csv("Datasets/winper.csv", index=False)
df = update_ELO(df)
df.to_csv("Datasets/ELO.csv", index=False)
get_rank = get_rank(df)
get_rank.to_csv("Datasets/get_rank.csv", index=False)
performance = calculate_team_performance(df)
performance.to_csv("Datasets/performance.csv", index=False)

  0%|          | 0/200 [00:00<?, ?it/s]

100%|██████████| 200/200 [00:00<00:00, 17032.36it/s]

  0%|          | 0/16034 [00:00<?, ?it/s]

  2%|▏         | 304/16034 [00:00<00:05, 3038.39it/s]

  4%|▍         | 623/16034 [00:00<00:04, 3119.91it/s]

  6%|▌         | 951/16034 [00:00<00:04, 3191.68it/s]

  8%|▊         | 1271/16034 [00:00<00:04, 3039.03it/s]

 10%|▉         | 1576/16034 [00:00<00:04, 2898.49it/s]

 12%|█▏        | 1898/16034 [00:00<00:04, 3001.41it/s]

 14%|█▍        | 2217/16034 [00:00<00:04, 3057.97it/s]

 16%|█▌        | 2524/16034 [00:00<00:04, 2902.42it/s]

 18%|█▊        | 2817/16034 [00:00<00:04, 2722.17it/s]

 19%|█▉        | 3096/16034 [00:01<00:04, 2738.90it/s]

 21%|██        | 3373/16034 [00:01<00:04, 2564.39it/s]

 23%|██▎       | 3633/16034 [00:01<00:05, 2465.51it/s]

 25%|██▍       | 3960/16034 [00:01<00:04, 2684.31it/s]

 27%|██▋       | 4318/16034 [00:01<00:03, 2936.70it/s]

 29%|██▉       | 4634/16034 [00:01<00:03, 2998.97it/s]

 31%|███       | 4953/16034 [00:01<00:03, 3049.65it/s]

 33%|███▎      | 5261/16034 [00:01<00:03, 3004.50it/s]

 35%|███▍      | 5564/16034 [00:01<00:03, 2835.78it/s]

 36%|███▋      | 5851/16034 [00:02<00:03, 2711.97it/s]

 38%|███▊      | 6128/16034 [00:02<00:03, 2727.00it/s]

 40%|████      | 6430/16034 [00:02<00:03, 2809.21it/s]

 42%|████▏     | 6730/16034 [00:02<00:03, 2863.83it/s]

 44%|████▍     | 7019/16034 [00:02<00:03, 2870.37it/s]

 46%|████▌     | 7370/16034 [00:02<00:02, 3055.08it/s]

 49%|████▊     | 7787/16034 [00:02<00:02, 3379.94it/s]

 51%|█████     | 8157/16034 [00:02<00:02, 3472.51it/s]

 53%|█████▎    | 8566/16034 [00:02<00:02, 3655.79it/s]

 56%|█████▌    | 8964/16034 [00:02<00:01, 3749.95it/s]

 58%|█████▊    | 9340/16034 [00:03<00:01, 3741.41it/s]

 61%|██████    | 9715/16034 [00:03<00:01, 3728.11it/s]

 63%|██████▎   | 10123/16034 [00:03<00:01, 3830.95it/s]

 66%|██████▌   | 10536/16034 [00:03<00:01, 3917.94it/s]

 68%|██████▊   | 10951/16034 [00:03<00:01, 3986.40it/s]

 71%|███████   | 11350/16034 [00:03<00:01, 3968.56it/s]

 73%|███████▎  | 11778/16034 [00:03<00:01, 4059.77it/s]

 76%|███████▌  | 12185/16034 [00:03<00:00, 4007.09it/s]

 78%|███████▊  | 12586/16034 [00:03<00:00, 3862.71it/s]

 81%|████████  | 13001/16034 [00:03<00:00, 3937.92it/s]

 84%|████████▎ | 13396/16034 [00:04<00:00, 3924.01it/s]

 86%|████████▌ | 13790/16034 [00:04<00:00, 3856.52it/s]

 89%|████████▊ | 14206/16034 [00:04<00:00, 3942.39it/s]

 91%|█████████ | 14601/16034 [00:04<00:00, 3851.43it/s]

 94%|█████████▎| 15014/16034 [00:04<00:00, 3932.14it/s]

 96%|█████████▌| 15414/16034 [00:04<00:00, 3950.51it/s]

 99%|█████████▊| 15810/16034 [00:04<00:00, 3910.70it/s]

100%|██████████| 16034/16034 [00:04<00:00, 3370.52it/s]

In [3]:
df.head()

,Year,Home_Team,Home_Score,Away_Score,Away_Team,Date,Margin,Home_Away_Draw,Prob_Home,Prob_Away,Home_Rating_Updated,Away_Rating_Updated
0,1893,Wales,12,11,England,1/7/1893,1,1.0,0.606,0.394,1510.914965,1489.085035
1,1893,Ireland,0,4,England,2/4/1893,-4,0.0,0.621,0.379,1460.01428,1529.070755
2,1893,Scotland,0,9,Wales,2/4/1893,-9,0.0,0.591,0.409,1445.553543,1565.361422
3,1893,Ireland,0,0,Scotland,2/20/1893,0,0.5,0.626,0.374,1460.01428,1445.553543
4,1893,England,0,8,Scotland,3/4/1893,-8,0.0,0.714,0.286,1466.373156,1508.251142

In [4]:
df.tail()

,Year,Home_Team,Home_Score,Away_Score,Away_Team,Date,Margin,Home_Away_Draw,Prob_Home,Prob_Away,Home_Rating_Updated,Away_Rating_Updated
16029,2026,Stormers,24,31,Connacht,4/18/2026,-7,0.0,0.603,0.397,1596.441754,1699.326718
16030,2026,Tokyo Sungoliath,22,27,Kubota Spears,4/18/2026,-5,0.0,0.289,0.711,1469.826056,1742.516892
16031,2026,Toyota Verblitz,24,38,Kobelco Kobe Steelers,4/18/2026,-14,0.0,0.218,0.782,1477.524331,1821.881709
16032,2026,US Montauban,22,47,RC Toulonnais,4/18/2026,-25,0.0,0.175,0.825,1038.258754,1428.317695
16033,2026,Yokohama Canon Eagles,33,15,Urayasu D-Rocks,4/18/2026,18,1.0,0.816,0.184,1332.972469,1105.758387